# Database Schema Configuration
SCHEMA_TABLES = [  """
Table: amenities
Columns:
    - id (INT, primary key)
    - name (VARCHAR(100))
    - vrbo_name (VARCHAR(100))
    - slug (VARCHAR(100))
    - image (TEXT)
    - status (BOOLEAN)
    - has_deleted (BOOLEAN)
    - created_by (INT)
    - updated_by (INT)
    - created_at (DATETIME)
    - updated_at (DATETIME)
    - is_key_amenity (BOOLEAN)
""",
"""

Table: resorts
Columns:
    - id (INT, primary key)
    - uploaded_from (VARCHAR(50))
    - default_view (VARCHAR(100))
    - creator_id (INT)
    - brand_id (INT, foreign key to brands.id)
    - name (VARCHAR(200))
    - slug (VARCHAR(200))
    - checkin_age (INT)
    - country_code (VARCHAR(10))
    - address (TEXT)
    - lattitude (DECIMAL(10,6))
    - longitude (DECIMAL(10,6))
    - dist_lat (DECIMAL(10,6))
    - dist_long (DECIMAL(10,6))
    - country (VARCHAR(100))
    - city (VARCHAR(100))
    - state (VARCHAR(100))
    - zip (VARCHAR(20))
    - county (VARCHAR(100))
    - associated_city (VARCHAR(100))
    - region (VARCHAR(100))
    - place_of_interest (TEXT)
    - neighbourhood (TEXT)
    - other (TEXT)
    - telephone (VARCHAR(20))
    - website (TEXT)
    - highlight_quote (TEXT)
    - description (TEXT)
    - additional_info (TEXT)
    - award_title (VARCHAR(200))
    - award_content (TEXT)
    - hotel_class_stars (DECIMAL(2,1))
    - children_family (BOOLEAN)
    - pets_friendly (BOOLEAN)
    - events_allowed (BOOLEAN)
    - smoking_allowed (BOOLEAN)
    - number_of_rooms (INT)
    - house_keeping (BOOLEAN)
    - min_price (DECIMAL(10,2))
    - max_price (DECIMAL(10,2))
    - additional_fees (TEXT)
    - verified_markup_fee (DECIMAL(10,2))
    - non_verified_markup_fee (DECIMAL(10,2))
    - check_in_time (VARCHAR(10))
    - check_out_time (VARCHAR(10))
    - cancelation_policy (TEXT)
    - damage_policy (TEXT)
    - resort_rules (TEXT)
    - additional_rules (TEXT)
    - nearest_airport (VARCHAR(100))
    - tripadvisor_location_id (VARCHAR(50))
    - tripadvisor_id (VARCHAR(50))
    - google_rating_id (VARCHAR(50))
    - review_url (TEXT)
    - google_rating (DECIMAL(2,1))
    - user_ratings_total (INT)
    - google_rating_default (DECIMAL(2,1))
    - vacatia_id (VARCHAR(50))
    - rci_id (VARCHAR(50))
    - rci_resort_id (VARCHAR(50))
    - destination_id (INT)
    - is_featured (BOOLEAN)
    - destination_featured (BOOLEAN)
    - top_21_resort (BOOLEAN)
    - price_starts_from (DECIMAL(10,2))
    - discount_percentage (DECIMAL(5,2))
    - popular (BOOLEAN)
    - details_verified (BOOLEAN)
    - descriptions_verified (BOOLEAN)
    - services_verified (BOOLEAN)
    - policies_verified (BOOLEAN)
    - partners_verified (BOOLEAN)
    - images_verified (BOOLEAN)
    - why_we_love_it (TEXT)
    - good_to_know (TEXT)
    - featured_amenities (TEXT)
    - meta_title (VARCHAR(255))
    - meta_description (TEXT)
    - page_title (VARCHAR(255))
    - meta_keywords (TEXT)
    - status (BOOLEAN)
    - is_open_availability (BOOLEAN)
    - has_deleted (BOOLEAN)
    - bookingpal_id (VARCHAR(50))
    - bookingpal_status (VARCHAR(50))
    - resort_sug_notify (BOOLEAN)
    - sitemp_name (VARCHAR(255))
    - updated_by (INT)
    - created_at (DATETIME)
    - updated_at (DATETIME)
    - last_activated_at (DATETIME)
""",
"""
Table: resort_amenities
Columns:
    - id (INT, primary key)
    - resort_id (INT, foreign key to resorts.id)
    - amenity_id (INT, foreign key to amenities.id)
    - created_at (DATETIME)
    - updated_at (DATETIME)
""",
"""

Table: brands
Columns:
    - id (INT, primary key)
    - is_concierge (BOOLEAN)
    - is_resort_request (BOOLEAN)
    - uploaded_from (VARCHAR(50))
    - name (VARCHAR(200))
    - slug (VARCHAR(200))
    - url (TEXT)
    - certificate_url (TEXT)
    - image (TEXT)
    - hero_image (TEXT)
    - h1_banner_title (VARCHAR(255))
    - h2_banner_subtitle (TEXT)
    - cta_btn_label (VARCHAR(100))
    - additional_rules (TEXT)
    - resort_rules (TEXT)
    - damage_policy (TEXT)
    - cancelation_policy (TEXT)
    - is_featured (BOOLEAN)
    - status (BOOLEAN)
    - brand_order (INT)
    - is_brand_page (BOOLEAN)
    - brand_page_status (BOOLEAN)
    - meta_title (VARCHAR(255))
    - meta_description (TEXT)
    - has_deleted (BOOLEAN)
    - created_by (INT)
    - updated_by (INT)
    - created_at (DATETIME)
    - updated_at (DATETIME)
    - last_activated_at (DATETIME)
""",
"""

Table: locations
Columns:
    - id (INT UNSIGNED, primary key)
    - locatable_id (INT UNSIGNED)
    - locatable_type (VARCHAR(255))
    - address (VARCHAR(255))
    - lattitude (VARCHAR(255))
    - longitude (VARCHAR(255))
    - country (VARCHAR(255))
    - city (VARCHAR(255))
    - state (VARCHAR(255))
    - zip (VARCHAR(255))
    - region (VARCHAR(255))
    - is_featured (INT UNSIGNED)
    - image (VARCHAR(300))
    - created_at (TIMESTAMP)
    - updated_at (TIMESTAMP)
""",
"""


Table: location_types
Columns:
    - id (INT UNSIGNED, primary key)
    - resort_id (INT UNSIGNED, foreign key to resorts.id)
    - resort_location_master_id (INT)
    - types (VARCHAR(255))
    - status (VARCHAR(255))
    - created_at (TIMESTAMP)
    - updated_at (TIMESTAMP)
""",
"""

Table: listings
Columns:
    - id (INT(10) UNSIGNED, primary key, auto_increment)
    - unique_hash (VARCHAR(255), nullable)
    - dvc_id (INT(10) UNSIGNED, not null, default 0)
    - rw_redweek_id (VARCHAR(255), not null, default '0')
    - rci_listing_id (VARCHAR(255), nullable, default '0')
    - hawaii_id (VARCHAR(255), not null, default '0')
    - is_concierge (INT(10) UNSIGNED, not null, default 0)
    - is_pt (TINYINT(1), not null, default 0)
    - is_frontend (TINYINT(1), not null, default 0)
    - push_to_vrbo (TINYINT(1), not null, default 0)
    - push_to_koala (TINYINT(1), not null, default 1)
    - is_arbitrage (INT(11), not null, default 0)
    - ownerrez_property_id (INT(11), not null, default 0)
    - unique_listing_code (VARCHAR(100), nullable)
    - owner_id (INT(10) UNSIGNED, not null)
    - is_test (TINYINT(1), not null, default 0)
    - host_assigned (VARCHAR(255), not null, default '1')
    - resort_id (INT(10) UNSIGNED, not null)
    - unit_type_id (INT(10) UNSIGNED, not null)
    - pro_unit_type_id (INT(10) UNSIGNED, not null)
    - import_history_id (INT(11), nullable, default 0)
    - unit_rate_id (INT(11), not null, default 0)
    - brand_id (INT(11), not null, default 0)
    - nights (VARCHAR(255), nullable)
    - min_nights (VARCHAR(255), nullable)
    - currency_id (INT(10) UNSIGNED, not null)
    - currency_code (VARCHAR(100), nullable)
    - currency_code_original (VARCHAR(100), nullable)
    - price_night (VARCHAR(255), nullable)
    - price_type (VARCHAR(20), nullable)
    - fixed_or_floating (VARCHAR(20), nullable)
    - total_price_original (VARCHAR(255), nullable)
    - price_night_original (VARCHAR(255), nullable)
    - price_min_nights (VARCHAR(255), nullable)
    - price_min_nights_original (VARCHAR(255), nullable)
    - comparable_price (VARCHAR(50), nullable)
    - comparable_price_original (VARCHAR(50), nullable)
    - comparison_status (VARCHAR(255), not null, default 'pending')
    - check_in (DATETIME, not null, default '0000-00-00 00:00:00')
    - check_out (DATETIME, not null, default '0000-00-00 00:00:00')
    - has_weekend (INT(11), not null, default 0)
    - exclusive (TINYINT(1), nullable, default 0)
    - check_in_day (VARCHAR(255), nullable)
    - reservation_no (VARCHAR(255), nullable)
    - bypass_reservation (VARCHAR(255), nullable)
    - is_your_reservation (INT(10) UNSIGNED, not null, default 0)
    - reservation_acc_holder (VARCHAR(100), nullable)
    - bypass_reservation_name (VARCHAR(255), nullable)
    - add_reservation_fee (VARCHAR(255), not null, default '1')
    - instant_book (VARCHAR(255), nullable)
    - availability_request (TINYINT(1), nullable, default 0)
    - status (VARCHAR(255), nullable)
    - is_available (TINYINT(1), not null, default 1)
    - draft_user_id (VARCHAR(255), nullable)
    - listing_type (VARCHAR(255), not null, default 'standard')
    - publish_type (VARCHAR(255), nullable)
    - points_used (INT(10) UNSIGNED, not null, default 0)
    - points_used_rebook (INT(10) UNSIGNED, not null, default 0)
    - points_year (YEAR(4), nullable, default '0000')
    - use_year_id (INT(11), not null, default 0)
    - bookingpal_id (VARCHAR(150), nullable)
    - distributed (VARCHAR(255), nullable, default '0')
    - virbo_id (VARCHAR(255), nullable)
    - airbnb_id (VARCHAR(255), nullable)
    - redweek_id (VARCHAR(255), nullable)
    - other_channel_id (VARCHAR(255), nullable)
    - bookingpal_status (VARCHAR(150), nullable)
    - koala_commission (VARCHAR(20), nullable)
    - vrbo_markup_commission (VARCHAR(10), nullable)
    - rw_commission (VARCHAR(255), not null, default '0')
    - rw_verified (VARCHAR(255), not null, default '0')
    - payout_fixed_price (VARCHAR(10), nullable)
    - confirm_dates_rentable (VARCHAR(255), nullable)
    - agree_terms (VARCHAR(255), nullable)
    - meta_title (MEDIUMTEXT, nullable)
    - meta_keywords (MEDIUMTEXT, nullable)
    - meta_description (MEDIUMTEXT, nullable)
    - current_step (INT(5), not null, default 1)
    - child_step (VARCHAR(20), nullable)
    - vip_featured_old (INT(11), not null, default 0)
    - hot_deal (TINYINT(1), nullable, default 0)
    - hot_deals_new (TINYINT(1), nullable, default 0)
    - hotdeal_toggled_at (DATETIME, not null, default '0000-00-00 00:00:00')
    - home_featured (TINYINT(1), nullable, default 0)
    - destination_featured (TINYINT(1), nullable, default 0)
    - vip_featured (TINYINT(1), nullable, default 0)
    - has_suggested_unit (INT(4), not null, default 0)
    - is_under_199 (TINYINT(1), not null, default 0)
    - has_deleted (INT(10) UNSIGNED, not null, default 0)
    - owner_verify_notify_count (INT(11), not null, default 0)
    - cancelation_policy_option (VARCHAR(255), nullable)
    - koala_report_id (INT(11), nullable, default 0)
    - ownerrez_push_status (VARCHAR(255), nullable, default '0')
    - data_date (DATE, nullable)
    - created_at (DATETIME, not null)
    - updated_at (DATETIME, not null)
    - deleted_at (DATETIME, nullable)
    """,
"""

Table: unit_type_amenities
Columns:
- id Primary (int(10), UNSIGNED, NOT NULL, AUTO_INCREMENT)
- unit_type_id Index (int(10), UNSIGNED, NOT NULL)
- amenity_id Index (int(10), UNSIGNED, NOT NULL, default 0)
- created_at (timestamp, NULL, default NULL)
- updated_at (timestamp, NULL, default NULL)
""",
"""

Table: destinations
Columns:
- id Primary (int(10), UNSIGNED, NOT NULL, AUTO_INCREMENT)
- name (varchar(255), utf8_unicode_ci, NULL, default NULL)
- slug (varchar(255), utf8_unicode_ci, NULL, default NULL)
- title (varchar(255), utf8_unicode_ci, NULL, default NULL)
- sub_title (varchar(500), utf8_unicode_ci, NULL, default NULL)
- banner_title (varchar(255), utf8_unicode_ci, NULL, default NULL)
- location (varchar(255), utf8_unicode_ci, NULL, default NULL)
- image (varchar(255), utf8_unicode_ci, NULL, default NULL)
- is_featured (int(10), UNSIGNED, NOT NULL, default 0)
- push_to_es (tinyint(1), NOT NULL, default 0)
- order (int(11), NULL, default NULL)
- meta_title (varchar(255), utf8_unicode_ci, NULL, default NULL)
- meta_keywords (varchar(255), utf8_unicode_ci, NULL, default NULL)
- meta_description (varchar(255), utf8_unicode_ci, NULL, default NULL)
- featured_in_search (varchar(255), utf8_unicode_ci, NOT NULL, default '0')
- search_order (int(11), NULL, default NULL)
- created_at (timestamp, NULL, default NULL)
- updated_at (timestamp, NULL, default NULL)
""",
"""

Table: resort_destinations
Columns:
- id Primary (int(10), UNSIGNED, NOT NULL, AUTO_INCREMENT)
- resort_id Index (int(10), UNSIGNED, NOT NULL)
- destination_id Index (int(10), UNSIGNED, NOT NULL)
- created_at (timestamp, NULL, default NULL)
- updated_at (timestamp, NULL, default NULL)
""",
"""

Table: unit_types
Columns:
- id (INT(10) UNSIGNED, primary key, auto_increment)
- creator_id (INT(10) UNSIGNED, NOT NULL, default 0)
- resort_id (INT(10) UNSIGNED, indexed, NOT NULL, default 0)
- is_frontend (TINYINT(1), NULL, default 0)
- is_rci_varies (TINYINT(1), NULL, default 0)
- varies_note (TEXT, nullable)
- current_step (INT(11), NULL, default 0)
- hot_deals (TINYINT(1), indexed, NOT NULL, default 0)
- residence_type_id (INT(10) UNSIGNED, indexed, NOT NULL, default 0)
- name (VARCHAR(255), indexed, nullable)
- web_view (VARCHAR(255), nullable)
- view (VARCHAR(255), nullable)
- slug (VARCHAR(255), nullable)
- tagline (MEDIUMTEXT, nullable)
- description (TEXT, nullable)
- headline (TEXT, nullable)
- meta_title (VARCHAR(255), nullable)
- meta_keywords (VARCHAR(255), nullable)
- meta_description (VARCHAR(255), nullable)
- page_title (VARCHAR(255), nullable)
- sleeps (VARCHAR(255), indexed, nullable)
- adults (VARCHAR(255), nullable)
- children (VARCHAR(255), nullable)
- guests (VARCHAR(255), nullable)
- bedrooms (VARCHAR(255), indexed, nullable)
- other_bedrooms (INT(11), nullable, default 0)
- bathrooms (VARCHAR(255), indexed, nullable)
- bathroom_amenities (TEXT, nullable)
- bathroom_sub_type (VARCHAR(255), nullable)
- living_rooms (VARCHAR(255), nullable)
- kitchen (VARCHAR(255), indexed, nullable)
- washer (VARCHAR(255), nullable)
- bedroom_type (VARCHAR(255), nullable)
- floor_plan (VARCHAR(255), nullable)
- average_price (VARCHAR(255), nullable)
- allow_handicap (VARCHAR(255), NOT NULL, default 'No')
- discount_lightbox (TEXT, nullable)
- discount_url (VARCHAR(350), nullable)
- square_footage (VARCHAR(255), nullable)
- area_units (VARCHAR(255), nullable)
- varies (INT(10) UNSIGNED, nullable, default 0)
- twin_bed (INT(10) UNSIGNED, nullable, default 0)
- double_bed (INT(10) UNSIGNED, nullable, default 0)
- queen_bed (INT(10) UNSIGNED, nullable, default 0)
- king_bed (INT(10) UNSIGNED, nullable, default 0)
- sleeper_sofa (INT(10) UNSIGNED, nullable, default 0)
- single_sleeper_sofa (INT(10) UNSIGNED, nullable, default 0)
- double_sleeper_sofa (INT(10) UNSIGNED, nullable, default 0)
- queen_sleeper_sofa (INT(10) UNSIGNED, nullable, default 0)
- king_sleeper_sofa (INT(10) UNSIGNED, nullable, default 0)
- murphy_bed (INT(10) UNSIGNED, nullable, default 0)
- single_murphy_bed (INT(10) UNSIGNED, nullable, default 0)
- double_murphy_bed (INT(10) UNSIGNED, nullable, default 0)
- queen_murphy_bed (INT(10) UNSIGNED, nullable, default 0)
- king_murphy_bed (INT(10) UNSIGNED, nullable, default 0)
- bunk_beds (INT(10) UNSIGNED, nullable, default 0)
- trundle_beds (INT(10) UNSIGNED, nullable, default 0)
- unit_type_order (INT(11), NOT NULL, default 0)
- cancelation_policy_option (VARCHAR(50), nullable)
- custom_days (VARCHAR(5), nullable)
- refund_before (VARCHAR(5), nullable)
- refund_after (VARCHAR(5), nullable)
- tax (VARCHAR(255), nullable)
- tax_percentage (VARCHAR(255), nullable)
- status (VARCHAR(30), indexed, nullable)
- is_suggest_unit (INT(11), NOT NULL, default 0)
- suggest_notify (INT(11), NOT NULL, default 0)
- has_deleted (INT(10) UNSIGNED, indexed, NOT NULL, default 0)
- is_pt_available (TINYINT(1), NOT NULL, default 0)
- push_to_vrbo (TINYINT(1), NULL, default 0)
- is_flexible_pt (TINYINT(1), NOT NULL, default 0)
- enable_partial_pay (INT(11), NOT NULL, default 0)
- partial_pay_percentage (INT(11), NULL, default 0)
- bookingpal_id (VARCHAR(150), NOT NULL)
- bookingpal_status (VARCHAR(150), NOT NULL)
- min_stay (INT(11), NOT NULL, default 3)
- max_stay (INT(11), NOT NULL, default 14)
- booking_type (VARCHAR(255), NOT NULL, default 'instant_book')
- rtb_host_id (INT(11), NOT NULL, default 0)
- booking_fee (VARCHAR(30), nullable)
- has_booking_fee (INT(11), NOT NULL, default 0)
- created_at (TIMESTAMP, nullable)
- updated_at (TIMESTAMP, nullable)
- last_activated_at (DATETIME, nullable)
""",
"""
Table: resort_key_amenities
Columns:
- id Primary (int(10), UNSIGNED, NOT NULL, AUTO_INCREMENT)
- resort_id Index (int(10), UNSIGNED, NOT NULL, default 0)
- amenity_id Index (int(10), UNSIGNED, NOT NULL, default 0)
- created_at (timestamp, NULL, default NULL)
- updated_at (timestamp, NULL, default NULL)
"""
]
RELATIONSHIPS = """
Relationships:

1. resorts → brands (Many-to-One)
2. resort_amenities → resorts (Many-to-One)
3. resort_amenities → amenities (Many-to-One)
4. booking → resorts (Many-to-One)
5. booking_date → booking (Many-to-One)
6. restricted_date → resorts (Many-to-One)
7.location_types → resorts (Many-to-One)
8.listings → owner (Many-to-One)
9.listings → resort (Many-to-One)
10.listings → unit_type (Many-to-One)
11.listings → pro_unit_type (Many-to-One)
12.listings → brand (Many-to-One)
13.listings → use_year (Many-to-One)
14.unit_types → resorts (Many-to-One)
15.unit_types → residence_types (Many-to-One)
16.unit_type_amenities → unit_types (Many-to-One)

17.unit_type_amenities → amenities (Many-to-One)

18.resort_destinations → resorts (Many-to-One)

19.resort_destinations → destinations (Many-to-One)

20.resort_key_amenities → resorts (Many-to-One)

21.resort_key_amenities → amenities (Many-to-One)
"""